"""
Django settings for TimeSeries project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tzfq5_io437!#kjw#ndg8gua^q*rk8@dtu!sc@@h157t^v=lgp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition
import django
from django.utils.translation import gettext
django.utils.translation.ugettext = gettext

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'TimeSeriesBase',
    'UserManagement',
    'UserAdmin',
    'DashboardAPI',
    'widget_tweaks',
    'import_export',
    'auditlog',
    'debug_toolbar',
    'fontawesome_5',
    'rest_framework',
    'ckeditor',
    'django_extensions',

    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
     "debug_toolbar.middleware.DebugToolbarMiddleware",
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

ROOT_URLCONF = 'TimeSeries.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TimeSeries.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
import os
STATIC_URL = 'static/'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'



MEDIA_ROOT=os.path.join(BASE_DIR,"media/")
MEDIA_URL='/media/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

#Custom User
AUTH_USER_MODEL = 'UserManagement.CustomUser'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = 'login/'
LOGIN_REDIRECT_URL = 'index'

#EMAIL

#DEFAULT_FROM_EMAIL = 'mikiyasmebrate2656@gmail.com'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587  # TLS port for Gmail
EMAIL_HOST_USER = 'beteltesfu15@gmail.com'
EMAIL_HOST_PASSWORD = 'rfwnocfedtsunpyd' # Replace with your actual Gmail password
EMAIL_USE_TLS = True  # Correct for port 587
EMAIL_USE_SSL = False  # Only one of TLS/SSL should be True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

#itdx avkv bkab armz  
TELEGRAM_APP_API_ID = '27306345'
TELEGRAM_APP_API_HASH = '2e140b6adb1aa4aaa03fdbb9aa6a343e'
BOT_TOKEN = '7005304926:AAFZKj_rIetG7WRZDu6GRzQhV-LQplxdOAg'
CHAT_ID = '688326285'
BOT_URL = "http://api.telegram.org/bot%s/"%BOT_TOKEN

#itdx avkv bkab armz  


#REDACTOR_wysiwyg_EDITOR
REDACTOR_OPTIONS = {'lang': 'en'}
REDACTOR_UPLOAD = 'uploads/'


from pathlib import Path
import logging
import warnings

# Django settings
BASE_DIR = Path(__file__).resolve().parent.parent

# Your other settings...

# Configure logging to suppress specific warnings
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'ignore_ckeditor_warning': {
            '()': 'django.utils.log.CallbackFilter',
            'callback': lambda record: 'django-ckeditor bundles CKEditor 4.22.1 which isn\'t supported anymore' not in record.getMessage(),
        },
    },
    'handlers': {
        'console': {
            'level': 'WARNING',
            'filters': ['ignore_ckeditor_warning'],
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}

# Suppress specific django-ckeditor warning using warnings module
warnings.filterwarnings(
    "ignore",
    message=r"django-ckeditor bundles CKEditor 4.22.1 which isn't supported anymore",
    module=r"ckeditor",
)

DJANGO_WYSIWYG_FLAVOR = 'yui'  # Default
DJANGO_WYSIWYG_FLAVOR = 'ckeditor'  # Requires you to also place the ckeditor files here:
DJANGO_WYSIWYG_MEDIA_URL = STATIC_URL + "ckeditor/"